### ISSUE TITLE
Struggling to export a document to PDF containing handwritten notes

### ISSUE THREAD

**Issue by HerrNamenlos123** [daledesilva/obsidian_ink#113]
First of all, thank you so much for your work on this plugin. In my time in college I have come to realize how valuable time can be.
I first discovered "ink" a long time ago, just after it was released, but I had to resort to other solutions as it was lacking in features. A few months ago I re-discovered it and was amazed how far it has come, and I am using it since then to write all my college notes.

Unfortunately, I have an exam in a few days and I need to print all my notes to paper.

**Describe the bug**
I have Markdown documents with multiple Ink handwritten Notes, and I need to export the document, so that i can print it. Whenever I try to export the page (Using the builtin PDF export and multiple other export plugins, the notes are always completely wrong and unreadable.

**Video or screenshots**

![Image](https://github.com/user-attachments/assets/2ed626d2-5000-4658-986b-03ccffa91e79)
Built-in export:
![Image](https://github.com/user-attachments/assets/3fd06c27-c3e2-40de-a036-d1c6c6207061)

Better Export Plugin:
![Image](https://github.com/user-attachments/assets/72eaf607-78d2-41e7-9c20-84a1cd287b46)

**To Reproduce**
1. Create a new markdown document and add handwritten notes
2. Write something
3. Export as PDF

**Expected behavior**
Export should work

**Desktop:**
- **Device & OS**: Lenovo Yoga 7i, Fedora 41
- **Plugin version**: 0.3.3
- **Obsidian version**: 1.7.7

**Additional context**
To be able to print the notes, ideally the PDF Export should work, but I am fine with any other workaround to print the notes, besides screenshotting it and killing my printer's black ink :)
If you know of any workaround please let me know as I do need it printed within a few days unfortunately.

**Comment by daledesilva** [comment]
Oh wow. I'm actually surprised it even showed up at all when printing. I haven't worked on that at all yet.
I have two quick hacks for you.

1.
If you look up how to add a CSS snippet to Obsidian, you can add this one and it should expand the ink embeds by the height you set. If you find it's still cropping some embeds, make the height larger.
- Unfortunately it's going to affect ecah and every embed the same (Unless you go and edit each ones height manually before printing each page).
```css
.ddc_ink_resize-container {
    height: 1500px !important;
}
```

2.
Another option is to take screenshots, and is probably quicker if you want to customise each height.
I know you were worried about blank ink, but if you switch obsidian to light mode first then it will invert.



Apologies that you're in this pickle and sorry i can't get a solution to you for your exams.
I hope the above helps get you there quickly!

**Comment by HerrNamenlos123** [comment]
Thank you for your quick response! You are right, I ended up just screenshotting everything in light mode and printing the images, it was tedious but it worked.

I think this issue can be kept open as I think this is quite an important feature and I am surprised not more people ran into this.

Backing story:
> My main criteria on my college-note-taking journey was actually an easy way to export notes to PDF for printing and sharing, without locking me into an eco-system. That removes almost all cloud-based tools from the list.
>Most of my friends use OneNote and their main pain point is actually the infinite canvas, which does not map to A4 PDF properly.
>Obsidian was almost perfect for me, it was just too slow to type LaTeX during lectures. So i used the Excalidraw Plugin but it again has issues with PDF <-> infinite canvas mapping.
>Your Plugin gives me the best of both worlds, having a solid Document format that can be exported to A4, with occasional handwritten formulas inbetween. The PDF Export would make it a complete solution :)

TLDR thank you very much for your work and I will continue to use the plugin and track progress :)

**Comment by HerrNamenlos123** [comment]
Plus, I also tried with a Drawing, and at least in the Better Exporter Plugin all drawings are visible, the height is just wrong and they overlap weirdly. Meaning, there is probably not even a lot of work to do, besides the height of each section everything looks fine.

**Comment by daledesilva** [comment]
I'll definitely leave this open, and thanks for all the info.

I'm currently rewriting how all drawings are implemented so that they're standard SVGs embeds - which means this issue will be fixed in the next update (which is probably a month away).

**Comment by MerlinBlatterer** [comment]
+1 For me the whole thing is missing
Edit View and Reading View:
<div style="display: flex; gap: 10px; align-items: flex-start;">

  <img src="https://github.com/user-attachments/assets/48daf9d1-aad7-48cf-9cac-f455a9a1eade" width="49%" />

  <img src="https://github.com/user-attachments/assets/b8eb5af1-82ed-46d3-9243-118bbc3a0e52" width="49%" />
</div>



<details> <summary>CSS (print layout rules) Disabling doesnt change anything</summary>

```css

@media print {
  /* pagebreak before all ## headings */
  h2 {
    page-break-before: always;
  }

  h3,
  h4 {
    page-break-after: avoid;
  }

  pre,
  blockquote {
    page-break-inside: avoid;
  }

  /* use double <hr> ('---') to indicate a page break */
  hr + hr {
    page-break-before: always;
    visibility: hidden;
  }

  :not(hr) + hr {
    visibility: hidden;
  }

  :not(hr) + hr + :not(hr):not(h2) {
    border-top: 1px solid black;
    padding-top: 2em;
  }
  
  /* keep text immediately after image together */
  img + * {
    page-break-before: avoid;
  }
}
```
</details>
