### ISSUE TITLE
SVG Export for Handwritten Notes with Light/Dark Mode Support

### ISSUE THREAD

**Issue by fugohan** [daledesilva/obsidian_ink#75]
## The Idea

The core idea is to add a function to the Command Palette of Obsidian that allows users to export handwritten notes as SVG files for web display, particularly in a Digital Garden context. This function would utilize the existing SVG code stored as an attribute in the .writing file, with some modifications.

## Why? How Would It Help?

1. **Improved Portability**: SVG files are vector-based and scalable, meaning they can be displayed on various devices and in different sizes without losing quality.

2. **Web Compatibility**: SVG is a widely used web format that can be easily embedded in HTML, making it perfect for Digital Gardens.

3. **Accessibility**: Handwritten notes could be shared more easily and used in various contexts, both within Obsidian and on the web.

4. **Flexibility**: The proposed CSS approach allows for dynamic adjustments to light and dark modes, enhancing readability in different environments.

5. **Digital Garden Integration**: This feature would bridge the gap between Obsidian's internal note-taking and public-facing Digital Gardens.

## Implementation Details

1. **Existing SVG Data**: The SVG code is already present as an attribute in the .writing file. This existing data will be the foundation for the export function.

2. **Style Addition**: The export function will add the necessary CSS style to the existing SVG code to ensure proper rendering in both light and dark modes.

3. **Character Replacement**: All instances of '\"' in the existing SVG code will be replaced with '"' to ensure proper formatting and compatibility.

4. **Export Process**:
   - Extract the SVG code from the .writing file
   - Add the CSS style to the SVG code
   - Replace '\"' with '"' throughout the SVG code
   - Save the modified SVG as a new file for web use

## Examples and References

CSS style to be added to the SVG:

```css
<style>
  :root {
    --bg-color: transparent;
    --stroke-color: #000;
    --fill-color: #000;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg-color: #333333;
      --stroke-color: #fff;
      --fill-color: #fff;
    }
  }
  svg {
    background-color: var(--bg-color);
  }
  path, line, text {
    stroke: var(--stroke-color);
    fill: var(--fill-color);
  }
  .interactive {
    cursor: pointer;
    transition: opacity 0.3s ease;
  }
  .interactive:hover {
    opacity: 0.7;
  }
</style>

```

## Acknowledgments

I appreciate all the hard work you’ve put into developing and improving Obsidian. Your efforts have made a significant impact on users like me, and I look forward to seeing how this feature can enhance the experience even further!
